Repository cu-webteam/d8-platform, pull requests merged in 2018-08, with the labels that each got.

#5 Misc
  docroot/sites/default/settings.php
  factory-hooks/db-update/db-update.sh
Labels: good first issue

#20 generated aliases for current sites using the command blt recipes:alias:init:acquia
  drush/sites/documentation.site.yml
  drush/sites/financialaidnew.site.yml
  drush/sites/loginssotest.site.yml
  drush/sites/mil.site.yml
  drush/sites/publicsafety.site.yml
  drush/sites/reservations.site.yml
  drush/sites/testsitewarning.site.yml
Labels: Acquia, review

#21 Front page layout
  docroot/themes/custom/cu2017/css/screen.css
  docroot/themes/custom/cu2017/css/style.css
  docroot/themes/custom/cu2017/cu2017.layouts.yml
  docroot/themes/custom/cu2017/sass/custom/_frontpage.scss
  docroot/themes/custom/cu2017/sass/style.scss
  docroot/themes/custom/cu2017/templates/layouts/front-page-classic.html.twig
  docroot/themes/custom/cu2017/templates/layouts/front-page-two-column.html.twig
Labels: review

#22 Update sso config script
  sso-config.sh
Labels: review

#24 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: review

#23 Generate issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: review

#25 adding updated news view and news template.
  config/default/views.view.cu_news.yml
  docroot/themes/custom/cu2017/templates/views/views-view-fields--cu-news--page-1.html.twig
Labels: review

#30 first brush with permissions for manager and editor.
  config/default/user.role.editor.yml
  config/default/user.role.manager.yml
Labels: review

#31 Post install
  factory-hooks/post-install/post-install.php
Labels: review

#33 Post install
  factory-hooks/post-install/post-install.php
Labels: review

#34 Roles
  config/default/filter.format.full_html.yml
  config/default/filter.format.plain_text.yml
  config/default/filter.format.raw_html.yml
  config/default/filter.format.rich_text.yml
  config/default/user.role.editor.yml
  config/default/user.role.manager.yml
Labels: review

#36 updated permissions based on UCOM feedback.
  config/default/user.role.editor.yml
  config/default/user.role.manager.yml
Labels: review

#35 Front page layout
  docroot/libraries/slick-carousel/slick/slick-theme.scss
  docroot/themes/custom/cu2017/css/style.css
  docroot/themes/custom/cu2017/cu2017.libraries.yml
  docroot/themes/custom/cu2017/images/front-page/arrows-circle-left.png
  docroot/themes/custom/cu2017/images/front-page/arrows-circle-right.png
  docroot/themes/custom/cu2017/images/front-page/left-circle-arrow.png
  docroot/themes/custom/cu2017/images/front-page/right-circle-arrow.png
  docroot/themes/custom/cu2017/js/main.js
  docroot/themes/custom/cu2017/sass/custom/_base.scss
  docroot/themes/custom/cu2017/sass/custom/_frontpage.scss
  docroot/themes/custom/cu2017/sass/custom/_main.scss
  docroot/themes/custom/cu2017/sass/custom/_slider.scss
  docroot/themes/custom/cu2017/templates/layouts/front-page-classic.html.twig
  docroot/themes/custom/cu2017/templates/node/node--slide.html.twig
  docroot/themes/custom/cu2017/templates/page/page--front.html.twig
  docroot/themes/custom/cu2017/templates/page/page.html.twig
Labels: review

#38 Adding a lot of role permissions for manager after testing.
  config/default/user.role.editor.yml
  config/default/user.role.manager.yml
Labels: review

#39 Docs
  .travis.yml
  README.md
  config/default/views.view.cu_news.yml
  docroot/themes/custom/cu2017/cu2017.theme
  docroot/themes/custom/cu2017/templates/node/node--content-page.html.twig
  docroot/themes/custom/cu2017/templates/node/node--links.html.twig
  docroot/themes/custom/cu2017/templates/views/views-view-fields--cu-news--page-1.html.twig
  docs/DEPLOYMENT.md
  docs/TEMPLATE.md
  docs/UCOM/BUILDING_SITE_IN_ACSF.md
  docs/UCOM/TABLE_OF_CONTENTS.md
  factory-hooks/db-update/db-update.sh
Labels: review

#40 Docs
  docs/UCOM/BUILDING_SITE_IN_ACSF.md
  docs/images/create_new_site.png
  docs/images/installation_profile.png
  docs/images/select_group.png
Labels: review

#41 Docs
  docs/UCOM/BUILDING_SITE_IN_ACSF.md
Labels: review

#43 Docs
  config/default/block.block.headerbackgroundimage.yml
  config/default/block.block.mainnavigation.yml
  docroot/themes/custom/cu2017/css/style.css
  docroot/themes/custom/cu2017/js/main.js
  docroot/themes/custom/cu2017/sass/core/_typography.scss
  docroot/themes/custom/cu2017/sass/custom/_frontpage.scss
  docroot/themes/custom/cu2017/sass/custom/_main.scss
  docroot/themes/custom/cu2017/sass/custom/_sitename.scss
  docroot/themes/custom/cu2017/sass/custom/_slider.scss
  docroot/themes/custom/cu2017/sass/style.scss
  docroot/themes/custom/cu2017/templates/html.html.twig
  docroot/themes/custom/cu2017/templates/layouts/front-page-classic.html.twig
  docs/UCOM/TABLE_OF_CONTENTS.md
  docs/UCOM/TESTING.md
  docs/UCOM/VIEWS_BLOCKS.md
Labels: review

#45 Docs
  docs/UCOM/FRONT_PAGE_CLASSIC.md
Labels: review

#48 update sso-config script to accept an argument instead of using a pro…
  factory-hooks/post-install/post-install.php
  sso-config.sh
Labels: review

#49 Post install
  drush/sites/logintestduplicate.site.yml
  drush/sites/sitecreationtest.site.yml
  drush/sites/sitecreationtest2.site.yml
  drush/sites/sitecreationtest3.site.yml
  drush/sites/sitecreationtest4.site.yml
  drush/sites/sitecreationtest5.site.yml
  sso-config.sh
Labels: review
